name: Publish Package
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - run: bash ${GITHUB_WORKSPACE}/build.sh
    - run: wasm-pack pack
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - run: |
        cd ${GITHUB_WORKSPACE}/pkg
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
